<?PHP header("Content-Type: text/html; charset=UTF-8",true);
if(!defined('INITIALIZED'))
	exit;
$main_content .= '
<h3>The Store</h3>
The Store is an interface that is accessible directly from within Game. It offers players a very convenient way to buy a wide range of Game products  for Tibia Coins without having to leave the game. What is more, most offered products like Mounts, a Character Name Change, a Transportation Service or Premium Time are available right away after the purchase. No relog necessary.<br><h3>Tibia Coins</h3>

Tibia Coins are a special currency in Game, which you can buy in the Webshop. They are available in packages of different sizes and can be used to buy character-based Extra Services, Mounts, Outfits, Blessings, XP Boosts, House Equipment, Runes, Potions, Premium Time and other Useful Things. Tibia Coins are available to all characters on an account. Once bought, they are automatically assigned to the account and immediately available ingame.<br>
Tibia Coins can be gifted to other characters, even on other game worlds. They can also be traded via the Market. Both premium and free account players can place buy and sell offers to trade Tibia Coins. However, Tibia Coins bought with one of the following payment methods cannot be gifted or traded in the first 6 months after the purchase:<br><ul>
<li>Credit/Debit Card in the Webshop</li><li>PayPal in the Webshop</li></ul><a name="interface_store"></a><h3>Store Interface</h3>

The Store can be entered either via the little coin symbol in the inventory or via the button "Store" in the  "General Controls" if you are using the Flash client.<br><br><b>Your current balance:</b><br>
Here you can see how many Tibia Coins you currently own on your account.<br><br><b>Categories:</b><br>
There are various categories from which players can choose: Premium Time, Extra Services, Blessings, Potions, Runes, Mounts, Outfits, House Equipment, XP Boosts and Useful Things. Moreover, you might see categories which feature (new) products or products on sale. If you select one of these categories, all products belonging to this category are displayed under Products in the large field to the right.
<br><br><center><img src="/layouts/tibiacom/images/gameguides/store.jpg" width="539" height="460"><br><i></p>Stand-Alone Client</i><br></center><br><b>Products:</b><br>
In this field, all products of a category are listed. Products which are greyed out are not available for this character. Either, you own the product already or you do not fulfil the requirements for the purchase (e.g. you can only buy Addons for Basic Outfits your character already owns). If you select one of the products, two buttons will appear - "Details" and "Buy Now". Under "Details" you can learn more about the specific product. If you like to purchase the selected product, click on "Buy Now". A dialog will open up in which you are asked to confirm the purchase.<br>
Note that you will buy a product instantly without any confirmation if you have previously disabled this confirmation dialog. You can do so either in the dialog itself or in the General Options.<br>
Keep in mind that you will purchase a product always for the character with which you are online during the purchase. Of course, Premium Time is valid for the whole account.
<br><br><b>History:</b><br>
In this list you can see all of your Tibia Coins transactions. All Tibia Coins that were added to your account are displayed in green, marked with a "plus" in front of it. Tibia Coins that were subtracted are shown in red, prefixed by a "minus". In the column "description" you can see on what you have spent your Tibia Coins or where you received them from.<br>You can also check your Tibia Coins History via your account management page on the website.<br><br><b>Get Tibia Coins:</b><br>
Clicking on this button will bring you to the Webshop on the Tibia website where you can purchase Tibia Coins. For more information, please have a look at the section Ordering Premium Time, Tibia Coins or Account-Based Extra Services.
<br><br><b>Gift Tibia Coins:</b><br>
If you click on this symbol, a dialog opens up which allows you to gift transferable Tibia Coins to characters of other accounts.<br>
First enter the name of the character that should receive the Tibia Coins. You can enter any character, no matter on which game world he or she lives. Make sure that you have spelled the character name correctly, because there is no way to get Tibia Coins back that you have gifted to someone else. As Tibia Coins are valid for the whole account, it is of course not possible to gift Tibia Coins to characters on your own account. Finally, choose the amount of Tibia Coins you like to gift. Note that the amount can only be raised in steps of 25. Of course, you cannot gift more Tibia Coins than you have got on your account. If you are sure you have entered the correct character name and selected the correct amount of Tibia Coins you like to gift, click on "Okay" to finalise the process. The Tibia Coins will arrive at the recipient immediately and can be used by all characters of the recipients account.				
';
?>